[package]
name = "kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bitflags = "2.8.0"
buddy_system_allocator = "0.11.0"
log = "0.4.22"
sbi-rt = {version = "0.0.3", features = ["legacy"]}


